#!/usr/bin/perl

use strict;
use warnings;

require Mojolicious::Commands;
Mojolicious::Commands->start_app('Mojo::HelloMojo');

=encoding utf8

=head1 NAME

hello_mojo - The Mojolicious command system

=head1 SYNOPSIS

  $ hello_mojo --help

=head1 DESCRIPTION

List and run L<Mojolicious> commands as described in
L<Mojolicious::Commands>.

=head1 SEE ALSO

L<Mojolicious>, L<Mojolicious::Guides>, L<http://mojolicio.us>.

=cut
